require "conf.nvim-tree"
require "conf.telescope"
require "conf.aerial"
require "conf.nvim-scrollbar"
require "conf.gitsigns"
require "conf.lualine"
require "conf.trouble"
require "conf.dressing"
require "conf.nvim-notify"
require "conf.barbar"
require "conf.auto-session"
require "conf.whichkey"
require "conf.lspconfig"

require "keymaps"

require "lsp"
